name: build

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install deno
        uses: denolib/setup-deno@master

      - name: Run deno
        run: |
          git config --local user.email "dmdefine6@gmail.com"
          git config --local user.name "typeofNaN"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.ACTIONS_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          deno run --unstable --allow-net --allow-read --allow-write --importmap=import_map.json mod.ts
          git add .
          git commit -m "get data by github actions"
          git push
